name             'handler_dsl_demo'
maintainer       'Chef Software, Inc.'
maintainer_email 'jdunn@getchef.com'
license          'Apache 2.0'
description      'Installs/Configures handler_dsl_demo'
long_description 'Installs/Configures handler_dsl_demo'
version          '0.1.0'
